import { clampChroma } from 'culori';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const L_STEPS = 65;
const H_STEPS = 256;

type Family = 'ok' | 'cie';
type Gamut = 'srgb' | 'display-p3';

const RGB_GAMUT: Record<Gamut, string> = { srgb: 'rgb', 'display-p3': 'p3' };
const CFG: Record<Family, { mode: 'oklch' | 'lch'; lMax: number; ceiling: number }> = {
  ok: { mode: 'oklch', lMax: 1, ceiling: 0.5 }, // above any sRGB/P3 OKLCH chroma
  cie: { mode: 'lch', lMax: 100, ceiling: 160 }, // above any sRGB/P3 LCH chroma
};

function sample(family: Family, gamut: Gamut): { b64: string; cmax: number } {
  const { mode, lMax, ceiling } = CFG[family];
  const raw = new Float64Array(L_STEPS * H_STEPS);
  let cmax = 0;
  for (let li = 0; li < L_STEPS; li++) {
    const l = (li / (L_STEPS - 1)) * lMax;
    for (let hi = 0; hi < H_STEPS; hi++) {
      const h = (hi / H_STEPS) * 360;
      let c = 0;
      if (li > 0 && li < L_STEPS - 1) {
        const clamped = clampChroma({ mode, l, c: ceiling, h } as never, mode, RGB_GAMUT[gamut]);
        c = (clamped as { c?: number }).c ?? 0;
      }
      raw[li * H_STEPS + hi] = c;
      if (c > cmax) cmax = c;
    }
  }
  // Serialize as explicit little-endian bytes so the payload is host-independent
  // (the decoder reads it back little-endian too).
  const bytes = new Uint8Array(raw.length * 2);
  for (let i = 0; i < raw.length; i++) {
    const v = Math.round((raw[i]! / cmax) * 65535);
    bytes[2 * i] = v & 0xff;
    bytes[2 * i + 1] = (v >> 8) & 0xff;
  }
  const b64 = Buffer.from(bytes).toString('base64');
  return { b64, cmax };
}

const NAMES: Record<Family, Record<Gamut, string>> = {
  ok: { srgb: 'oklchSrgb', 'display-p3': 'oklchP3' },
  cie: { srgb: 'lchSrgb', 'display-p3': 'lchP3' },
};
const FILES: Record<Family, Record<Gamut, string>> = {
  ok: { srgb: 'oklch-srgb.ts', 'display-p3': 'oklch-display-p3.ts' },
  cie: { srgb: 'lch-srgb.ts', 'display-p3': 'lch-display-p3.ts' },
};

const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'luts');
mkdirSync(outDir, { recursive: true });

for (const family of ['ok', 'cie'] as Family[]) {
  for (const gamut of ['srgb', 'display-p3'] as Gamut[]) {
    const { b64, cmax } = sample(family, gamut);
    const name = NAMES[family][gamut];
    const mode = CFG[family].mode;
    // /*#__PURE__*/ lets bundlers drop any LUT the consumer doesn't import.
    const src =
      `// Generated by scripts/build-luts.ts — do not edit.\n` +
      `import { decodeLut } from './decode';\n\n` +
      `export const ${name} = /*#__PURE__*/ decodeLut(\n  '${mode}',\n  '${b64}',\n  ${cmax},\n  ${L_STEPS},\n  ${H_STEPS},\n);\n`;
    writeFileSync(join(outDir, FILES[family][gamut]), src);
    console.log(`wrote ${FILES[family][gamut]} (cmax=${cmax.toFixed(4)})`);
  }
}
